---
ci_test: false
log: true
ansible_network_os: "ios"
ansible_user: "ansible"
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33646665303538616431616437396462653463313361636361366562636434326538346237333337
          6339323336616230336662346333333839396535366237330a393531626230303561373465356533
          66346333326433643035626661343234303062326366376436316331386462306235306134303735
          3639666434323965660a653936396465613465356138306563373831666663353163636639663439
          6639
...
